[workspace]
resolver = "2"
members = [
  "redb",
  "sled",
  "stats"
]

[workspace.dependencies]
crossbeam = "0.8.4"
serde = "1"
clap = { version = "4.5.4", features = ["derive"] }
tokio = "1.37"
stats = { path = "stats" }