name: ReDB (Bench)

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Compile
        run: cargo build --release --bin redb
      - name: Bench
        run: RUST_BACKTRACE=1 EXE=target/release/redb sh bench.sh